// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// GibbsPosteriorC
RcppGSL::vector<double> GibbsPosteriorC(int dimension, double regularite, int nb_points_a_generer, int iterations, double sd_instrum, int nb_fonctionsTendance, unsigned long int random_seed, std::vector<std::string> words, RcppGSL::matrix<double> planXP, RcppGSL::vector<double> observations, RcppGSL::matrix<double> tendanceR);
RcppExport SEXP GibbsPosteriorC_GibbsPosteriorC(SEXP dimensionSEXP, SEXP regulariteSEXP, SEXP nb_points_a_genererSEXP, SEXP iterationsSEXP, SEXP sd_instrumSEXP, SEXP nb_fonctionsTendanceSEXP, SEXP random_seedSEXP, SEXP wordsSEXP, SEXP planXPSEXP, SEXP observationsSEXP, SEXP tendanceRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< double >::type regularite(regulariteSEXP);
    Rcpp::traits::input_parameter< int >::type nb_points_a_generer(nb_points_a_genererSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type sd_instrum(sd_instrumSEXP);
    Rcpp::traits::input_parameter< int >::type nb_fonctionsTendance(nb_fonctionsTendanceSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type random_seed(random_seedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type words(wordsSEXP);
    Rcpp::traits::input_parameter< RcppGSL::matrix<double> >::type planXP(planXPSEXP);
    Rcpp::traits::input_parameter< RcppGSL::vector<double> >::type observations(observationsSEXP);
    Rcpp::traits::input_parameter< RcppGSL::matrix<double> >::type tendanceR(tendanceRSEXP);
    __result = Rcpp::wrap(GibbsPosteriorC(dimension, regularite, nb_points_a_generer, iterations, sd_instrum, nb_fonctionsTendance, random_seed, words, planXP, observations, tendanceR));
    return __result;
END_RCPP
}
// quarantedeux
int quarantedeux();
RcppExport SEXP GibbsPosteriorC_quarantedeux() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(quarantedeux());
    return __result;
END_RCPP
}
